Bokstavskombination

diff --git a/Scripts/OSX/backup b/Scripts/OSX/backup
--- a/Scripts/OSX/backup
+++ b/Scripts/OSX/backup
@@ -9,54 +9,54 @@
 
 # Usage: backup
 
-device_name=Keychain
-encrypted_image=/Volumes/$device_name/Backup.sparseimage
-backup_destination=/Volumes/Backup
+device=Keychain
+sparseimage=/Volumes/$device/Backup.sparseimage
+destination=/Volumes/Backup
 
 directories=(
-  Development
-  Documents
-  Dropbox
-  Library/Application\ Support/Alfred\ 2/Alfred.alfredpreferences
-  Library/Application\ Support/OpenEmu
-  Library/Safari/Bookmarks.plist
-  Movies
-  Music/FLAC
-  Music/GBS
-  Music/MP3
-  Music/NSFe
-  Music/Ringtones
-  Pictures
-  Projects
-  School
-  Sites
-  Storage
-  Web\ Archives
-  YouTube
+  ~/Development
+  ~/Documents
+  ~/Dropbox
+  ~/Library/Application\ Support/Alfred\ 2/Alfred.alfredpreferences
+  ~/Library/Application\ Support/OpenEmu
+  ~/Library/Safari/Bookmarks.plist
+  ~/Movies
+  ~/Music/FLAC
+  ~/Music/GBS
+  ~/Music/MP3
+  ~/Music/NSFe
+  ~/Music/Ringtones
+  ~/Pictures
+  ~/Projects
+  ~/School
+  ~/Sites
+  ~/Storage
+  ~/Web\ Archives
+  ~/YouTube
 )
 
-if [[ ! -f $encrypted_image ]]; then
-  echo "File '$encrypted_image' does not exist!"
-  return 1
+if [[ ! -f $sparseimage ]]; then
+  echo "File '$sparseimage' does not exist! Exiting..."
+  exit 1
 fi
 
 echo "Mounting encrypted image file."
-hdiutil attach -noverify $encrypted_image
+hdiutil attach -noverify $sparseimage
 
-if [[ ! -d $backup_destination ]]; then
-  echo "\nDirectory '$backup_destination' does not exist!"
-  return 1
+if [[ ! -d $destination ]]; then
+  echo "\nDirectory '$destination' does not exist! Exiting..."
+  exit 1
 fi
 
 for directory in $directories; do
-  if [[ -d $directory ]]; then
-    print -P "\n%B%F{green}Backing up directory ~/$directory.%f%b"
-    rsync --archive --delete --exclude=Dropbox/.dropbox.cache --human-readable --verbose ~/$directory $backup_destination
+  if [[ -d $directory || -f $directory ]]; then
+    print -P "\n%B%F{green}Backing up directory ${directory/$HOME/~}.%f%b"
+    rsync --archive --delete --exclude=Dropbox/.dropbox.cache --human-readable --verbose $directory $destination
   else
-    echo "\nDirectory '$directory' not found! Exiting..."
+    echo "\nDirectory '${directory/$HOME/~}' not found! Exiting..."
     exit 1
   fi
 done
 
 echo "\nUnmounting encrypted image file and device."
-hdiutil detach $backup_destination && diskutil eject $device_name
+hdiutil detach $destination && diskutil eject $device
diff --git a/Scripts/OSX/backup2s b/Scripts/OSX/backup2s
--- a/Scripts/OSX/backup2s
+++ b/Scripts/OSX/backup2s
@@ -28,14 +28,19 @@ directories2=(
   ~/Music/MP3
 )
 
+if [[ ! -d $destination2 ]]; then
+  echo "\nDirectory '$destination' does not exist! Exiting..."
+  exit 1
+fi
+
 echo "Backing up directories to server '$server'."
 
 for directory in $directories; do
-  if [[ -d $directory ]]; then
-    print -P "\n%B%F{green}Backing up directory $directory.%f%b"
+  if [[ -d $directory || -f $directory ]]; then
+    print -P "\n%B%F{green}Backing up directory ${directory/$HOME/~}.%f%b"
     rsync --archive --delete --human-readable --progress $directory -e ssh ${server}:$destination
   else
-    echo "\nDirectory '$directory' not found! Exiting..."
+    echo "\nDirectory '${directory/$HOME/~}' not found! Exiting..."
     exit 1
   fi
 done
@@ -43,11 +48,11 @@ done
 echo "\nBacking up directories to server '$server2'."
 
 for directory in $directories2; do
-  if [[ -d $directory ]]; then
-    print -P "\n%B%F{green}Backing up directory $directory.%f%b"
+  if [[ -d $directory || -f $directory ]]; then
+    print -P "\n%B%F{green}Backing up directory ${directory/$HOME/~}.%f%b"
     rsync --archive --delete --human-readable --progress $directory $destination2
   else
-    echo "\nDirectory '$directory' not found! Exiting..."
+    echo "\nDirectory '${directory/$HOME/~}' not found! Exiting..."
     exit 1
   fi
 done
diff --git a/Scripts/validate b/Scripts/validate
--- a/Scripts/validate
+++ b/Scripts/validate
@@ -33,8 +33,8 @@ for arg; do
   results=$(curl --form "uploaded_file=@${arg:t};type=text/html" --form output=json --silent http://validator.w3.org/check)
 
   if [[ $? -gt 0 ]]; then
-    echo "Failed at getting results!"
-    return 1
+    echo "Failed at getting results! Exiting..."
+    exit 1
   fi
 
   # Change back to the old directory. Otherwise the check for if the next file
