...

diff --git a/Scripts/chkp b/Scripts/chkp
--- a/Scripts/chkp
+++ b/Scripts/chkp
@@ -10,36 +10,37 @@
 
 project_dir=~/Projects
 
-echo "Checking status of projects."
+if [[ ! -d $project_dir ]]; then
+  echo "Directory '$project_dir' not found! Exiting..."
+  exit 1
+elif [[ -z $(echo $project_dir/*(N)) ]]; then
+  echo "Directory '$project_dir' is empty! Exiting..."
+  exit 1
+fi
 
 for directory in $project_dir/*; do
   cd $directory
 
   if [[ -n $(git rev-list origin..HEAD 2> /dev/null) ]]; then
-    print -P "\n%B%F{cyan}${directory:t}:%f%b"
+    print -P "%B%F{cyan}${directory:t}:%f%b"
   elif [[ -n $(git status --short 2> /dev/null) ]]; then
-    print -P "\n%B%F{red}${directory:t}:%f%b"
+    print -P "%B%F{red}${directory:t}:%f%b"
   elif [[ -d .git ]]; then
     clean_repos+=($directory:t)
     continue
   else
-    not_repos+=($directory:t)
     continue
   fi
 
   git status --branch --short
+  echo
 done
 
 if [[ ${#clean_repos} -gt 0 ]]; then
-  print -P "\n%B%F{green}Clean repo(s):%f%b"
+  print -P "%B%F{green}Clean repo(s):%f%b"
   for repo_name in $clean_repos; do
     echo " * $repo_name"
   done
-fi
-
-if [[ ${#not_repos} -gt 0 ]]; then
-  print -P "\n%B%F{blue}Not Git repo(s):%f%b"
-  for dir_name in $not_repos; do
-    echo " * $dir_name"
-  done
+else
+  echo "No clean repos found!"
 fi
