...
...

diff --git a/home/Scripts/validate b/home/Scripts/validate
--- a/home/Scripts/validate
+++ b/home/Scripts/validate
@@ -4,26 +4,31 @@
 
 if [[ $# == 1 ]]; then
   if [ -f $1 ]; then
-    COMMAND='curl -sF "uploaded_file=@$FILENAME;type=text/html" -F output=json http://validator.w3.org/check'
-    CURRENT_DIRECTORY=$PWD
-    DIRECTORY=$1:A:h
-    FILENAME=$1:t
+    if [[ $1 == *.html ]]; then
+      COMMAND='curl -sF "uploaded_file=@$FILENAME;type=text/html" -F output=json http://validator.w3.org/check'
+      CURRENT_DIRECTORY=$PWD
+      DIRECTORY=$1:A:h
+      FILENAME=$1:t
 
-    cd $DIRECTORY
-    RESULTS=$(eval $COMMAND)
-    if [[ $? -gt 0 ]]; then
-      echo "Failed at getting results!"
-      return 1
-    fi
-    cd $CURRENT_DIRECTORY
+      cd $DIRECTORY
+      RESULTS=$(eval $COMMAND)
+      if [[ $? -gt 0 ]]; then
+        echo "Failed at getting results!"
+        return 1
+      fi
+      cd $CURRENT_DIRECTORY
 
-    PARSED=$(echo $RESULTS | grep '"lastLine":')
+      PARSED=$(echo $RESULTS | grep '"lastLine":')
 
-    if [ ! -z $PARSED ]; then
-      echo "Found error(s) on line(s):\n"
-      echo $PARSED | sed 's/^[ \t]*"lastLine":/ /;s/,//g' | sort -g | uniq
+      if [ ! -z $PARSED ]; then
+        echo "Found error(s) on line(s):\n"
+        echo $PARSED | sed 's/^[ \t]*"lastLine":/ /;s/,//g' | sort -g | uniq
+      else
+        echo "No errors! :)"
+      fi
     else
-      echo "No errors! :)"
+      echo "File $1 does not end with html."
+      return 1
     fi
   else
     echo "File $1 does not exist."
